# Site settings
title: Swaggaaa's Blog # site title
description: >- # site description
  Consultant Software Engineer during the day, Security Researcher at night.
  Active on <a href="https://github.com/Swaggaaa" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Europe/Madrid # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
# repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Swaggaaa # author name
  bio: >- # tell to the world
    Consultant Software Engineer during the day, Security Researcher at night.
    Active on <a href="https://github.com/Swaggaaa" target="_blank" rel="noopener">@github</a>.
  username: Swaggaaa # social media username eg. github, twitter 
  email: theycallmeswaggaaa@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://sergibanyez.dev/blog"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

theme: jekyll-theme-midnight